FROM node:17-alpine3.15 as builder

RUN apk add --no-cache gcc g++ autoconf make pkgconfig git openssl \
    libressl curl-dev zip unzip supervisor nginx bash

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN npm install

CMD ["npm", "run", "serve"]


